"""empty message

Revision ID: 2be5ce40494c
Revises: 4bfff8b8216e
Create Date: 2025-09-24 02:50:27.531570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be5ce40494c'
down_revision = '4bfff8b8216e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - begin ###
    
    # Primero convertir los datos existentes
    # Crear columna temporal boolean
    op.add_column('user', sa.Column('is_admin_temp', sa.Boolean(), nullable=True))
    
    # Convertir datos: 'admin' -> True, cualquier otra cosa -> False
    op.execute("""
        UPDATE "user" 
        SET is_admin_temp = CASE 
            WHEN is_admin = 'admin' THEN TRUE 
            ELSE FALSE 
        END
    """)
    
    # Hacer la columna temporal no nullable
    op.alter_column('user', 'is_admin_temp', nullable=False)
    
    # Eliminar columna original
    op.drop_column('user', 'is_admin')
    
    # Renombrar columna temporal
    op.alter_column('user', 'is_admin_temp', new_column_name='is_admin')
    
    # Eliminar constraint unique de farm_name si existe
    try:
        op.drop_constraint('farm_farm_name_key', 'farm', type_='unique')
    except:
        pass  # Ignorar si no existe
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - begin ###
    
    # Revertir: Boolean -> String
    # Crear columna temporal string
    op.add_column('user', sa.Column('is_admin_temp', sa.VARCHAR(length=20), nullable=True))
    
    # Convertir datos: True -> 'admin', False -> 'user'
    op.execute("""
        UPDATE "user" 
        SET is_admin_temp = CASE 
            WHEN is_admin = TRUE THEN 'admin' 
            ELSE 'user' 
        END
    """)
    
    # Hacer la columna temporal no nullable con default
    op.alter_column('user', 'is_admin_temp', nullable=False, server_default='user')
    
    # Eliminar columna boolean
    op.drop_column('user', 'is_admin')
    
    # Renombrar columna temporal
    op.alter_column('user', 'is_admin_temp', new_column_name='is_admin')
    
    # Restaurar constraint unique de farm_name
    op.create_unique_constraint('farm_farm_name_key', 'farm', ['farm_name'])
    
    # ### end Alembic commands ###