"""empty message

Revision ID: 4bfff8b8216e
Revises: 
Create Date: 2025-08-18 01:35:20.110608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfff8b8216e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('is_admin', sa.String(length=20), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('salt', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_location', sa.String(length=100), nullable=False),
    sa.Column('farm_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_name'),
    sa.UniqueConstraint('user_id', 'farm_location', name='uix_user_farm_location'),
    sa.UniqueConstraint('user_id', 'farm_name', name='uix_user_farm_name')
    )
    op.create_table('diagnostic_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_diagnostic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm_images')
    op.drop_table('diagnostic_reports')
    op.drop_table('farm')
    op.drop_table('user')
    # ### end Alembic commands ###
