"""empty message

Revision ID: 5ec1f87df1d0
Revises: ce3b696de40c
Create Date: 2025-08-07 04:20:20.514053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec1f87df1d0'
down_revision = 'ce3b696de40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('image_type', sa.String(length=50), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ndvi_images')
    op.drop_table('aerial_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aerial_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aerial_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name='aerial_images_farm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aerial_images_pkey'),
    sa.UniqueConstraint('aerial_url', name='aerial_images_aerial_url_key')
    )
    op.create_table('ndvi_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ndvi_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name='ndvi_images_farm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ndvi_images_pkey'),
    sa.UniqueConstraint('ndvi_url', name='ndvi_images_ndvi_url_key')
    )
    op.drop_table('farm_images')
    # ### end Alembic commands ###
