"""empty message

Revision ID: 63da375cf2e2
Revises: df3516a6a21a
Create Date: 2025-07-31 07:14:53.638506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63da375cf2e2'
down_revision = 'df3516a6a21a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint('user_avatar_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_avatar_key', ['avatar'])
        batch_op.alter_column('avatar',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
