"""empty message

Revision ID: ce3b696de40c
Revises: e6437b10955f
Create Date: 2025-08-06 05:56:04.670448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3b696de40c'
down_revision = 'e6437b10955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aerial_images', schema=None) as batch_op:
        batch_op.alter_column('aerial_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.alter_column('ndvi_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ndvi_images', schema=None) as batch_op:
        batch_op.alter_column('ndvi_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('aerial_images', schema=None) as batch_op:
        batch_op.alter_column('aerial_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
