"""empty message

Revision ID: e6437b10955f
Revises: 63da375cf2e2
Create Date: 2025-08-06 05:50:23.784288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6437b10955f'
down_revision = '63da375cf2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aerial_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('aerial_url', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aerial_url')
    )
    op.drop_table('aereal_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aereal_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('aereal_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name='aereal_images_farm_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aereal_images_pkey'),
    sa.UniqueConstraint('aereal_url', name='aereal_images_aereal_url_key')
    )
    op.drop_table('aerial_images')
    # ### end Alembic commands ###
